cache:
  untracked: true
  key: cache_${CI_COMMIT_REF_SLUG}
stages:
  - build

job_build:
  stage: build
  image: gitlab/dind
  script:
    - sed -i 's/{version}/1.3.17/' ./dockerfile/node-with-tool/Dockerfile
    - cd ./dockerfile/node-with-tool/
    - ./build
  only:
    - master
    - /^release.*$/
